# Generated by Django 5.2.2 on 2025-06-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_estudiantes/')),
            ],
        ),
    ]
